/*
 * PaperlessREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing CorrespondentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CorrespondentsApiTests : IDisposable
    {
        private CorrespondentsApi instance;

        public CorrespondentsApiTests()
        {
            instance = new CorrespondentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CorrespondentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CorrespondentsApi
            //Assert.IsType<CorrespondentsApi>(instance);
        }

        /// <summary>
        /// Test CreateCorrespondent
        /// </summary>
        [Fact]
        public void CreateCorrespondentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewCorrespondent? newCorrespondent = null;
            //instance.CreateCorrespondent(newCorrespondent);
        }

        /// <summary>
        /// Test DeleteCorrespondent
        /// </summary>
        [Fact]
        public void DeleteCorrespondentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.DeleteCorrespondent(id);
        }

        /// <summary>
        /// Test GetCorrespondents
        /// </summary>
        [Fact]
        public void GetCorrespondentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetCorrespondents();
        }

        /// <summary>
        /// Test UpdateCorrespondent
        /// </summary>
        [Fact]
        public void UpdateCorrespondentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //Correspondent? correspondent = null;
            //instance.UpdateCorrespondent(id, correspondent);
        }
    }
}
