services:
  paperless-rest:
    build:
      dockerfile: PaperlessREST/PaperlessREST/Dockerfile
    ports:
      - 9000:80
      - 9001:443

  paperless-services:
    build:
      dockerfile: PaperlessServices/PaperlessServices/Dockerfile
    ports:
      - 9002:80
      - 9003:443

  file-storage-service:
    build:
      dockerfile: FileStorageService/FileStorageService/Dockerfile
    ports:
      - 9004:80
      - 9005:443