services:
  paperless-rest:
    build: Project/PaperlessREST/
    ports:
      - 9000:80
      - 9001:443

  paperless-services:
    build: PaperlessServices/PaperlessServices/
    ports:
      - 9002:80
      - 9003:443

  file-storage-service:
    build: FileStorageService/FileStorageService/
    ports:
      - 9004:80
      - 9005:443