/*
 * PaperlessREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentType
        //private DocumentType instance;

        public DocumentTypeTests()
        {
            // TODO uncomment below to create an instance of DocumentType
            //instance = new DocumentType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentType
        /// </summary>
        [Fact]
        public void DocumentTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentType
            //Assert.IsType<DocumentType>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Match'
        /// </summary>
        [Fact]
        public void MatchTest()
        {
            // TODO unit test for the property 'Match'
        }

        /// <summary>
        /// Test the property 'MatchingAlgorithm'
        /// </summary>
        [Fact]
        public void MatchingAlgorithmTest()
        {
            // TODO unit test for the property 'MatchingAlgorithm'
        }

        /// <summary>
        /// Test the property 'IsInsensitive'
        /// </summary>
        [Fact]
        public void IsInsensitiveTest()
        {
            // TODO unit test for the property 'IsInsensitive'
        }

        /// <summary>
        /// Test the property 'DocumentCount'
        /// </summary>
        [Fact]
        public void DocumentCountTest()
        {
            // TODO unit test for the property 'DocumentCount'
        }
    }
}
