/*
 * PaperlessREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Document
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Document
        //private Document instance;

        public DocumentTests()
        {
            // TODO uncomment below to create an instance of Document
            //instance = new Document();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Document
        /// </summary>
        [Fact]
        public void DocumentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Document
            //Assert.IsType<Document>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Correspondent'
        /// </summary>
        [Fact]
        public void CorrespondentTest()
        {
            // TODO unit test for the property 'Correspondent'
        }

        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Fact]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }

        /// <summary>
        /// Test the property 'StoragePath'
        /// </summary>
        [Fact]
        public void StoragePathTest()
        {
            // TODO unit test for the property 'StoragePath'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

        /// <summary>
        /// Test the property 'Added'
        /// </summary>
        [Fact]
        public void AddedTest()
        {
            // TODO unit test for the property 'Added'
        }

        /// <summary>
        /// Test the property 'ArchiveSerialNumber'
        /// </summary>
        [Fact]
        public void ArchiveSerialNumberTest()
        {
            // TODO unit test for the property 'ArchiveSerialNumber'
        }

        /// <summary>
        /// Test the property 'OriginalFileName'
        /// </summary>
        [Fact]
        public void OriginalFileNameTest()
        {
            // TODO unit test for the property 'OriginalFileName'
        }

        /// <summary>
        /// Test the property 'ArchivedFileName'
        /// </summary>
        [Fact]
        public void ArchivedFileNameTest()
        {
            // TODO unit test for the property 'ArchivedFileName'
        }
    }
}
