/*
 * PaperlessREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NewTag
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewTagTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewTag
        //private NewTag instance;

        public NewTagTests()
        {
            // TODO uncomment below to create an instance of NewTag
            //instance = new NewTag();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewTag
        /// </summary>
        [Fact]
        public void NewTagInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewTag
            //Assert.IsType<NewTag>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

        /// <summary>
        /// Test the property 'Match'
        /// </summary>
        [Fact]
        public void MatchTest()
        {
            // TODO unit test for the property 'Match'
        }

        /// <summary>
        /// Test the property 'MatchingAlgorithm'
        /// </summary>
        [Fact]
        public void MatchingAlgorithmTest()
        {
            // TODO unit test for the property 'MatchingAlgorithm'
        }

        /// <summary>
        /// Test the property 'IsInsensitive'
        /// </summary>
        [Fact]
        public void IsInsensitiveTest()
        {
            // TODO unit test for the property 'IsInsensitive'
        }

        /// <summary>
        /// Test the property 'IsInboxTag'
        /// </summary>
        [Fact]
        public void IsInboxTagTest()
        {
            // TODO unit test for the property 'IsInboxTag'
        }
    }
}
